config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'home/index'
  resources :books
  resources :videogames
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/videogame.rb
class Videogame < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :release, :publisher, :rating, :genre)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/videogames_controller.rb
class VideogamesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_videogame, only: %i[ show edit update destroy ]

  # GET /videogames or /videogames.json
  def index
    @videogames = Videogame.all
  end

  # GET /videogames/1 or /videogames/1.json
  def show
  end

  # GET /videogames/new
  def new
    @videogame = Videogame.new
  end

  # GET /videogames/1/edit
  def edit
  end

  # POST /videogames or /videogames.json
  def create
    @videogame = Videogame.new(videogame_params)

    respond_to do |format|
      if @videogame.save
        format.html { redirect_to videogame_url(@videogame), notice: "Videogame was successfully created." }
        format.json { render :show, status: :created, location: @videogame }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @videogame.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videogames/1 or /videogames/1.json
  def update
    respond_to do |format|
      if @videogame.update(videogame_params)
        format.html { redirect_to videogame_url(@videogame), notice: "Videogame was successfully updated." }
        format.json { render :show, status: :ok, location: @videogame }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @videogame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videogames/1 or /videogames/1.json
  def destroy
    @videogame.destroy

    respond_to do |format|
      format.html { redirect_to videogames_url, notice: "Videogame was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_videogame
      @videogame = Videogame.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def videogame_params
      params.require(:videogame).permit(:name, :release, :publisher, :rating, :genre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/videogames_helper.rb
module VideogamesHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :release %>
    <%= form.number_field :release %>
  </div>

  <div class="field">
    <%= form.label :publisher %>
    <%= form.text_field :publisher %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Release</th>
      <th>Publisher</th>
      <th>Rating</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.release %></td>
        <td><%= book.publisher %></td>
        <td><%= book.rating %></td>
        <td><%= book.genre %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Release:</strong>
  <%= @book.release %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @book.rating %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @book.genre %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/home/index.html.erb
<h1>Bienvenido <%= current_user.email %></h1>
<a href="/videogames">Videojuegos</a>
<br>
<a href="/books">Libros</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevopsApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= (button_to "logout", destroy_user_session_path, method: :delete) if current_user  %>
    <%= yield %>
  </body>
</html>

app/views/videogames/_form.html.erb
<%= form_with(model: videogame, local: true) do |form| %>
  <% if videogame.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(videogame.errors.count, "error") %> prohibited this videogame from being saved:</h2>

      <ul>
        <% videogame.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :release %>
    <%= form.number_field :release %>
  </div>

  <div class="field">
    <%= form.label :publisher %>
    <%= form.text_field :publisher %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videogames/edit.html.erb
<h1>Editing Videogame</h1>

<%= render 'form', videogame: @videogame %>

<%= link_to 'Show', @videogame %> |
<%= link_to 'Back', videogames_path %>

app/views/videogames/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videogames</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Release</th>
      <th>Publisher</th>
      <th>Rating</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videogames.each do |videogame| %>
      <tr>
        <td><%= videogame.name %></td>
        <td><%= videogame.release %></td>
        <td><%= videogame.publisher %></td>
        <td><%= videogame.rating %></td>
        <td><%= videogame.genre %></td>
        <td><%= link_to 'Show', videogame %></td>
        <td><%= link_to 'Edit', edit_videogame_path(videogame) %></td>
        <td><%= link_to 'Destroy', videogame, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Videogame', new_videogame_path %>

app/views/videogames/new.html.erb
<h1>New Videogame</h1>

<%= render 'form', videogame: @videogame %>

<%= link_to 'Back', videogames_path %>

app/views/videogames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @videogame.name %>
</p>

<p>
  <strong>Release:</strong>
  <%= @videogame.release %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @videogame.publisher %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @videogame.rating %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @videogame.genre %>
</p>

<%= link_to 'Edit', edit_videogame_path(@videogame) %> |
<%= link_to 'Back', videogames_path %>